---
title: "Data Science and AI 2 Project"
author: "Gábor T. Mozol"
output: html_notebook
---

```{r}
library(tidyverse)
library(dplyr)
library(igraph)
library(ggraph)
library(svglite)
```

```{r}
my_wd <- getwd()
project <- file.path(my_wd)
#usethis::create_project(project, open = FALSE)
usethis::proj_set(project)
source(file.path(my_wd,"functions/functions_analysis.R"))
```

```{r}
ts_data_path = paste(getwd(),"/data/truth_social_data", sep="")
ts_nodes <- read_tsv_files(file.path(ts_data_path, "users"))
ts_edges <- read_tsv_files(file.path(ts_data_path, "follows"))
```

```{r}
ts_nodes <- ts_nodes %>% select(id, username)
ts_edges <- ts_edges %>% select(follower, followed)
```

```{r}
colnames(ts_nodes)<-c("id", "username")
colnames(ts_edges)<-c("source", "target")
```

```{r}
ts_nodes <- check_append_missing_nodes(ts_edges, ts_nodes)
```

```{r}
(g_ts <- igraph::graph_from_data_frame(
  d = ts_edges,
  directed = TRUE,
  vertices = ts_nodes
))
```
If you want to use the previously generated graph, you can load it in this way.
```{r}
g_ts <- read_graph(file.path(my_wd,"/graph/ts.csv"), "edgelist", directed=TRUE)
```

```{r}
g_ts_analysis <- graph_main_analysis(g_ts)
```

```{r}
cat("Order: ", g_ts_analysis$order, "\n")
cat("Size: ", g_ts_analysis$size, "\n")
cat("Degree range: ", g_ts_analysis$degree_min, " - ", g_ts_analysis$degree_max, "\n")
cat("Indegree range: ", g_ts_analysis$indegree_min, " - ", g_ts_analysis$indegree_max, "\n")
cat("Outdegree range: ", g_ts_analysis$outdegree_min, " - ", g_ts_analysis$outdegree_max, "\n")
cat("Clusters (weak / strong): ", g_ts_analysis$clusters$weak, " / ", g_ts_analysis$clusters$strong, "\n")
cat("Edge connectivity: ", g_ts_analysis$e_con, "\n")
cat("Vertex connectivity: ", g_ts_analysis$v_con, "\n")
cat("Diameter: ", g_ts_analysis$diameter, "\n")
cat("Average path length: ", g_ts_analysis$apl, "\n")
cat("Transitivity: ", g_ts_analysis$transitivity, "\n")
```

```{r}
write_graph(g_ts,file.path(my_wd,"/graph/ts.csv"),"edgelist")
```
